AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec