AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - "app/services/**/*"
RSpec/NestedGroups:
  Max: 5
require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
