version: '3'
services:
  database:
    image: postgres:16.1
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      tech_challenge_network:

volumes:
  postgres:

networks:
  tech_challenge_network:
    name: tech_challenge_network