name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: localhost
      MINIMUM_COVERAGE: 100.0

    services:
      database:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: transaction_fraud_detection_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Gems
        run: bundle install --jobs 4

      - name: Test
        run: bundle exec rspec

      - name: Lint
        run: bundle exec rubocop

      - name: Validate Coverage
        run: |
          covered_percent=$(cat coverage/coverage.json | jq -r '.metrics.covered_percent');
          re='^[+-]?[0-9]+([.||,][0-9]+)?$';
          if ! [[ $covered_percent =~ $re ]]; then 
            echo "WARNING :: Couldn't get coverage from artifact.";
            exit 0
          fi
          required_coverage=${{env.MINIMUM_COVERAGE}};
          if [ $covered_percent -le $required_coverage ]; then
            echo "Coverage ($covered_percent%) is below the required threshold of $required_coverage%.";
            exit 1
          else
            echo "Coverage ($covered_percent%) passed the required threshold of $required_coverage%."
          fi
